#### Statistics

In [1]:
import numpy as np

In [19]:
a = np.array([[1,5,2], [4,3,6]])
print(a)

[[1 5 2]
 [4 3 6]]


In [20]:
np.min(a, axis = 1)

array([1, 3])

In [21]:
np.max(a, axis = 1)

array([5, 6])

In [17]:
np.sum(a, axis = 0)

array([5, 7, 9])

In [22]:
np.sum(a, axis = 1)

array([ 8, 13])

#### Re-organizing arrays

In [30]:
before = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(before)

after = before.reshape(6,2)
print(after)

after2 = before.reshape(2, 2, 3) # converting 2d array to 3d array
print(after2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4,5,6])
v2 = np.array([7,8,9,10,11,12])

np.vstack([v1,v2])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [33]:
np.vstack([v1,v2,v1,v2])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [34]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])