In [1]:
import numpy as np

a = np.array([10,20, 30])
a

array([10, 20, 30])

In [3]:
b = np.array([2, 3, 4])
c = a * b
c

array([ 20,  60, 120])

In [5]:
d = np.array([[2,2,2], [3,3,3]])
print(d)

[[2 2 2]
 [3 3 3]]


In [9]:
# Get Dimension
d.ndim

2

In [10]:
# Get Shape
d.shape

(2, 3)

In [11]:
# Get Size
d.size

6

In [22]:
e = np.array([10, 20, 30], dtype='int16')
print(e.itemsize)
print(e.dtype)
print(e.nbytes)

2
int16
6


In [2]:
a = np.array([[1,2,3,4,5,100],[6,7,8,9,10,200]])
a

NameError: name 'np' is not defined

In [24]:
a.shape

(2, 5)

In [26]:
# Get a specific element
a[1, 3]

9

In [27]:
# Get a specific row
a[1, :]

array([ 6,  7,  8,  9, 10])

In [28]:
# Get a specific column
a[:, 3]

array([4, 9])

In [30]:
# entire array
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([  2,   4, 100])

In [38]:
a[0, 5] = 25
a

array([[  1,   2,   3,   4,   5,  25],
       [  6,   7,   8,   9,  10, 200]])

In [39]:
a[:, 2] = 555
a

array([[  1,   2, 555,   4,   5,  25],
       [  6,   7, 555,   9,  10, 200]])

In [40]:
a[1, :] = 888
a

array([[  1,   2, 555,   4,   5,  25],
       [888, 888, 888, 888, 888, 888]])