#### Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [10]:
a = np.array([1,2,3,4])
a += 2
a

array([3, 4, 5, 6])

In [20]:
a = np.array([1,2,3,4])
b = np.array([1, 0, 1, 0])
a + b
#np.add(a,b)
#np.subtract(a,b)

array([2, 2, 4, 4])

In [12]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
a = np.array([1,2,3,4])
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [ ]:
# for a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)